#! /bin/bash
 
 #--env HTTP_PROXY="http://192.168.19.1:10809" \
 #--env HTTPS_PROXY="http://192.168.19.1:10809" \
 #--env NO_PROXY="*.example.com,127.0.0.1" \
 
docker run -it --rm \
 --net nginx-network \
 -v /home/core/data/www/:/www \
 -v $(pwd):$(pwd) -w $(pwd) wenshunbiao/php:7.2.34 sh -c "php $*"
