#! /bin/bash
 
 #--env HTTP_PROXY="http://192.168.19.1:10809" \
 #--env HTTPS_PROXY="http://192.168.19.1:10809" \
 #--env NO_PROXY="*.example.com,127.0.0.1" \

if [ ! -f "/home/core/data/php82/php.ini" ]; then
   /home/core/docker/shell/i php82
fi

if [ ! -f "/home/core/data/php82/entrypoint.sh" ]; then
   cp /home/core/docker/php82/conf/entrypoint.sh /home/core/data/php82/entrypoint.sh
   chmod 755 /home/core/data/php82/entrypoint.sh
fi 

docker run --rm \
 --net nginx-network \
 -e ENABLE_LOG=0 \
 -v /home/core/data/php82:/php \
 -v /home/core/data/www/:/www \
 -v $(pwd):$(pwd) -w $(pwd) timeerror/php:8.2.29 sh -c "php $*"
