version: '3.8'

services:
  hoppscotch:
    image: hoppscotch/hoppscotch:latest
    container_name: hoppscotch
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8000}:${HOPP_AIO_ALTERNATE_PORT:-80}"
    env_file:
      - .env
    networks:
      - shared-network
networks:
  shared-network:
    external: true
    name: nginx-network